apps/blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.blog_list, name='list'),
    path('detail/<int:pk>/', views.blog_detail, name='detail'),
]

apps/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('coming-soon/', views.coming_soon, name='coming_soon'),
    path('404/', views.error_404, name='error_404'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('blogs/', include('apps.blogs.urls', namespace='blogs')),
    path('products/', include('apps.products.urls', namespace='products')),
    path('', include('apps.pages.urls', namespace='pages')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/pages/models.py
from django.db import models

class ContactModel(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=16)
    subject = models.CharField(max_length=255, null=True, blank=True)
    message = models.TextField()
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.subject}"

    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'


class AboutModel(models.Model):
    full_name = models.CharField(max_length=255)
    profession = models.CharField(max_length=255)
    self_photo = models.ImageField(upload_to='images/')
    facebook_url = models.URLField()
    twitter_url = models.URLField()
    instagram_url = models.URLField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.full_name}"

    class Meta:
        verbose_name = 'About'
        verbose_name_plural = 'Abouts'

templates/pages/about.html
{% extends 'layout/base.html' %}
{% load static %}
{% load i18n %}
{% block title %}{% trans "Molla - Bootstrap eCommerce Template" %}{% endblock %}
{% block content %}
<main class="main">
        	<div class="page-header text-center" style="background-image: url('{% static 'assets/images/page-header-bg.jpg' %}')">
        		<div class="container">
        			<h1 class="page-title">{% trans "About us 2" %}<span>{% trans "Pages" %}</span></h1>
        		</div>
        	</div>
            <nav aria-label="breadcrumb" class="breadcrumb-nav">
                <div class="container">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'pages:about' %}">{% trans "Home" %}</a></li>
                        <li class="breadcrumb-item"><a href="#">{% trans "Pages" %}</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{% trans "About us 2" %}</li>
                    </ol>
                </div>
            </nav>

            <div class="page-content pb-3">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-10 offset-lg-1">
                            <div class="about-text text-center mt-3">
                                <h2 class="title text-center mb-2">{% trans "Who We Are" %}</h2>
                                <p>{% blocktrans %}Sed pretium, ligula sollicitudin laoreet viverra, tortor libero sodales leo, eget blandit nunc tortor eu nibh. Suspendisse potenti. Sed egestas, ante et vulputate volutpat, uctus metus libero eu augue. Morbi purus libero, faucibus adipiscing, commodo quis, gravida id, est. Sed lectus. Praesent elementum hendrerit tortor. Sed semper lorem at felis.{% endblocktrans %}</p>
                                <img src="{% static 'assets/images/about/about-2/signature.png' %}" alt="signature" class="mx-auto mb-5">
                                <img src="{% static 'assets/images/about/about-2/img-1.jpg' %}" alt="image" class="mx-auto mb-6">
                            </div>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-lg-4 col-sm-6">
                            <div class="icon-box icon-box-sm text-center">
                                <span class="icon-box-icon">
                                    <i class="icon-puzzle-piece"></i>
                                </span>
                                <div class="icon-box-content">
                                    <h3 class="icon-box-title">{% trans "Design Quality" %}</h3>
                                    <p>{% blocktrans %}Sed egestas, ante et vulputate volutpat, eros pede semper est, vitae luctus metus libero eu augue.{% endblocktrans %}</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-sm-6">
                            <div class="icon-box icon-box-sm text-center">
                                <span class="icon-box-icon">
                                    <i class="icon-life-ring"></i>
                                </span>
                                <div class="icon-box-content">
                                    <h3 class="icon-box-title">{% trans "Professional Support" %}</h3>
                                    <p>{% blocktrans %}Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat.{% endblocktrans %}</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-sm-6">
                            <div class="icon-box icon-box-sm text-center">
                                <span class="icon-box-icon">
                                    <i class="icon-heart-o"></i>
                                </span>
                                <div class="icon-box-content">
                                    <h3 class="icon-box-title">{% trans "Made With Love" %}</h3>
                                    <p>{% blocktrans %}Pellentesque a diam sit amet mi ullamcorper vehicula. Nullam quis massa sit amet nibh viverra malesuada.{% endblocktrans %}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="mb-2"></div>

                <div class="bg-image pt-7 pb-5 pt-md-12 pb-md-9" style="background-image: url({% static 'assets/images/backgrounds/bg-4.jpg' %})">
                    <div class="container">
                        <div class="row">
                            <div class="col-6 col-md-3">
                                <div class="count-container text-center">
                                    <div class="count-wrapper text-white">
                                        <span class="count" data-from="0" data-to="40" data-speed="3000" data-refresh-interval="50">0</span>k+
                                    </div>
                                    <h3 class="count-title text-white">{% trans "Happy Customer" %}</h3>
                                </div>
                            </div>

                            <div class="col-6 col-md-3">
                                <div class="count-container text-center">
                                    <div class="count-wrapper text-white">
                                        <span class="count" data-from="0" data-to="20" data-speed="3000" data-refresh-interval="50">0</span>+
                                    </div>
                                    <h3 class="count-title text-white">{% trans "Years in Business" %}</h3>
                                </div>
                            </div>

                            <div class="col-6 col-md-3">
                                <div class="count-container text-center">
                                    <div class="count-wrapper text-white">
                                        <span class="count" data-from="0" data-to="95" data-speed="3000" data-refresh-interval="50">0</span>%
                                    </div>
                                    <h3 class="count-title text-white">{% trans "Return Clients" %}</h3>
                                </div>
                            </div>

                            <div class="col-6 col-md-3">
                                <div class="count-container text-center">
                                    <div class="count-wrapper text-white">
                                        <span class="count" data-from="0" data-to="15" data-speed="3000" data-refresh-interval="50">0</span>
                                    </div>
                                    <h3 class="count-title text-white">{% trans "Awards Won" %}</h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="bg-light-2 pt-6 pb-7 mb-6">
                    <div class="container">
                        <h2 class="title text-center mb-4">{% trans "Meet Our Team" %}</h2>

                        <div class="row">
                            {% for person in persons %}
                            <div class="col-sm-6 col-lg-3">
                                <div class="member member-2 text-center">
                                    <figure class="member-media">
                                        <img src="{{ person.self_photo.url }}" alt="{% trans 'member photo' %}">

                                        <figcaption class="member-overlay">
                                            <div class="social-icons social-icons-simple">
                                                <a href="{{ person.facebook_url }}" class="social-icon" title="{% trans 'Facebook' %}" target="_blank"><i class="icon-facebook-f"></i></a>
                                                <a href="{{ person.twitter_url }}" class="social-icon" title="{% trans 'Twitter' %}" target="_blank"><i class="icon-twitter"></i></a>
                                                <a href="{{ person.instagram_url }}" class="social-icon" title="{% trans 'Instagram' %}" target="_blank"><i class="icon-instagram"></i></a>
                                            </div>
                                        </figcaption>
                                    </figure>
                                    <div class="member-content">
                                        <h3 class="member-title">{{ person.full_name }}<span>{{ person.profession }}</span></h3>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>

                        <div class="text-center mt-3">
                            <a href="{% url 'blogs:list' %}" class="btn btn-sm btn-minwidth-lg btn-outline-primary-2">
                                <span>{% trans "LETS START WORK" %}</span>
                                <i class="icon-long-arrow-right"></i>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="container">
                    <div class="row">
                        <div class="col-lg-10 offset-lg-1">
                            <div class="brands-text text-center mx-auto mb-6">
                                <h2 class="title">{% trans "The world's premium design brands in one destination." %}</h2>
                                <p>{% blocktrans %}Phasellus hendrerit. Pellentesque aliquet nibh nec urna. In nisi neque, aliquet vel, dapibus id, mattis vel, nis{% endblocktrans %}</p>
                            </div>
                            <div class="brands-display">
                                <div class="row justify-content-center">
                                    <div class="col-6 col-sm-4 col-md-3">
                                        <a href="#" class="brand">
                                            <img src="{% static 'assets/images/brands/1.png' %}" alt="{% trans 'Brand Name' %}">
                                        </a>
                                    </div>

                                    <div class="col-6 col-sm-4 col-md-3">
                                        <a href="#" class="brand">
                                            <img src="{% static 'assets/images/brands/2.png' %}" alt="{% trans 'Brand Name' %}">
                                        </a>
                                    </div>

                                    <div class="col-6 col-sm-4 col-md-3">
                                        <a href="#" class="brand">
                                            <img src="{% static 'assets/images/brands/3.png' %}" alt="{% trans 'Brand Name' %}">
                                        </a>
                                    </div>

                                    <div class="col-6 col-sm-4 col-md-3">
                                        <a href="#" class="brand">
                                            <img src="{% static 'assets/images/brands/7.png' %}" alt="{% trans 'Brand Name' %}">
                                        </a>
                                    </div>

                                    <div class="col-6 col-sm-4 col-md-3">
                                        <a href="#" class="brand">
                                            <img src="{% static 'assets/images/brands/4.png' %}" alt="{% trans 'Brand Name' %}">
                                        </a>
                                    </div>

                                    <div class="col-6 col-sm-4 col-md-3">
                                        <a href="#" class="brand">
                                            <img src="{% static 'assets/images/brands/5.png' %}" alt="{% trans 'Brand Name' %}">
                                        </a>
                                    </div>

                                    <div class="col-6 col-sm-4 col-md-3">
                                        <a href="#" class="brand">
                                            <img src="{% static 'assets/images/brands/6.png' %}" alt="{% trans 'Brand Name' %}">
                                        </a>
                                    </div>

                                    <div class="col-6 col-sm-4 col-md-3">
                                        <a href="#" class="brand">
                                            <img src="{% static 'assets/images/brands/9.png' %}" alt="{% trans 'Brand Name' %}">
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
{% endblock %}

templates/pages/contact.html
{% extends 'layout/base.html' %}
{% load static %}
{% load i18n %}
{% block title %}Molla - Bootstrap eCommerce Template{% endblock %}
{% block content %}
<main class="main">
    <nav aria-label="breadcrumb" class="breadcrumb-nav border-0 mb-0">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'pages:home' %}">{% trans 'Home' %}</a></li>
                <li class="breadcrumb-item"><a href="#">{% trans 'Pages' %}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{% trans 'Contact us' %}</li>
            </ol>
        </div>
    </nav>

    <div class="container">
        <div class="page-header page-header-big text-center" style="background-image: url('{% static 'assets/images/contact-header-bg.jpg' %}')">
            <h1 class="page-title text-white">{% trans 'Contact us' %}<span class="text-white">{% trans 'keep in touch with us' %}</span></h1>
        </div>
    </div>

    <div class="page-content pb-0">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mb-2 mb-lg-0">
                    <h2 class="title mb-1">{% trans 'Contact Information' %}</h2>
                    <p class="mb-3">
                        {% blocktranslate %}
                        Vestibulum volutpat, lacus a ultrices sagittis, mi neque euismod dui, eu pulvinar nunc sapien ornare nisl.
                        {% endblocktranslate %}
                    </p>
                    <div class="row">
                        <div class="col-sm-7">
                            <div class="contact-info">
                                <h3>{% trans 'The Office' %}</h3>
                                <ul class="contact-list">
                                    <li><i class="icon-map-marker"></i>{% trans '70 Washington Square South New York, NY 10012, United States' %}</li>
                                    <li><i class="icon-phone"></i><a href="tel:+92423567">+92 423 567</a></li>
                                    <li><i class="icon-envelope"></i><a href="mailto:info@Molla.com">info@Molla.com</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="contact-info">
                                <h3>{% trans 'Office Hours' %}</h3>
                                <ul class="contact-list">
                                    <li><i class="icon-clock-o"></i><span class="text-dark">{% trans 'Monday-Saturday' %}</span> <br>11am-7pm ET</li>
                                    <li><i class="icon-calendar"></i><span class="text-dark">{% trans 'Sunday' %}</span> <br>11am-6pm ET</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Contact Form -->
                <div class="col-lg-6">
                    <h2 class="title mb-1">{% trans 'Got Any Questions?' %}</h2>
                    <p class="mb-2">{% trans 'Use the form below to get in touch with the sales team' %}</p>

                    <!-- Success/Error Messages -->
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} contact-alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form method="post" action="" class="contact-form mb-3">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-sm-6">
                                <label for="id_name" class="sr-only">{% trans 'Name' %}</label>
                                <input type="text" name="name" class="form-control {% if form.name.errors %}is-invalid{% endif %}"
                                       id="id_name" placeholder="{% trans 'Name' %} *">
                                {% for error in form.name.errors %}
                                    <div class="invalid-feedback">{{ error }}</div>
                                {% endfor %}
                            </div>

                            <div class="col-sm-6">
                                <label for="id_email" class="sr-only">Email</label>
                                <input type="email" name="email" class="form-control {% if form.email.errors %}is-invalid{% endif %}"
                                       id="id_email" placeholder="Email *">
                                {% for error in form.email.errors %}
                                    <div class="invalid-feedback">{{ error }}</div>
                                {% endfor %}
                            </div>
                        </div>

                        <!-- Phone + Subject yonma-yon -->
                        <div class="row mt-3">
                            <div class="col-sm-6">
                                <label for="id_phone" class="sr-only">{% trans 'Phone' %}</label>
                                <input type="text" name="phone" class="form-control {% if form.phone.errors %}is-invalid{% endif %}"
                                       id="id_phone" placeholder="{% trans 'Phone' %}">
                                {% for error in form.phone.errors %}
                                    <div class="invalid-feedback">{{ error }}</div>
                                {% endfor %}
                            </div>
                            <div class="col-sm-6">
                                <label for="id_subject" class="sr-only">{% trans 'Subject' %}</label>
                                <input type="text" name="subject" class="form-control {% if form.subject.errors %}is-invalid{% endif %}"
                                       id="id_subject" placeholder="{% trans 'Subject' %}">
                                {% for error in form.subject.errors %}
                                    <div class="invalid-feedback">{{ error }}</div>
                                {% endfor %}
                            </div>
                        </div>

                        <!-- Message -->
                        <label for="id_message" class="sr-only">{% trans 'Message' %}</label>
                        <textarea name="message" class="form-control {% if form.message.errors %}is-invalid{% endif %}"
                                  cols="30" rows="4" id="id_message" required
                                  placeholder="{% trans 'Message' %} *"></textarea>
                        {% for error in form.message.errors %}
                            <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}

                        <button type="submit" class="btn btn-outline-primary-2 btn-minwidth-sm mt-3">
                            <span>{% trans 'SUBMIT' %}</span>
                            <i class="icon-long-arrow-right"></i>
                        </button>
                    </form>
                </div>
            </div>

            <hr class="mt-4 mb-5">

            <div class="stores mb-4 mb-lg-5">
                <h2 class="title text-center mb-3">{% trans 'Our Stores' %}</h2>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="store">
                            <div class="row">
                                <div class="col-sm-5 col-xl-6">
                                    <figure class="store-media mb-2 mb-lg-0">
                                        <img src="{% static 'assets/images/stores/img-1.jpg' %}" alt="image">
                                    </figure>
                                </div>
                                <div class="col-sm-7 col-xl-6">
                                    <div class="store-content">
                                        <h3 class="store-title">Wall Street Plaza</h3>
                                        <address>88 Pine St, New York, NY 10005, USA</address>
                                        <div><a href="tel:+19878766543">+1 987-876-6543</a></div>
                                        <h4 class="store-subtitle">{% trans 'Store Hours:' %}</h4>
                                        <div>{% trans 'Monday - Saturday' %} 11am to 7pm</div>
                                        <div>{% trans 'Sunday' %} 11am to 6pm</div>
                                        <a href="#" class="btn btn-link" target="_blank"><span>{% trans 'View Map' %}</span><i class="icon-long-arrow-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <div class="store">
                            <div class="row">
                                <div class="col-sm-5 col-xl-6">
                                    <figure class="store-media mb-2 mb-lg-0">
                                        <img src="{% static 'assets/images/stores/img-2.jpg' %}" alt="image">
                                    </figure>
                                </div>
                                <div class="col-sm-7 col-xl-6">
                                    <div class="store-content">
                                        <h3 class="store-title">{% trans 'One New York Plaza' %}</h3>
                                        <address>88 Pine St, New York, NY 10005, USA</address>
                                        <div><a href="tel:+19878766543">+1 987-876-6543</a></div>
                                        <h4 class="store-subtitle">{% trans 'Store Hours:' %}</h4>
                                        <div>{% trans 'Monday - Friday' %} 9am to 8pm</div>
                                        <div>{% trans 'Saturday' %} - 9am to 2pm</div>
                                        <div>{% trans 'Sunday - Closed' %}</div>
                                        <a href="#" class="btn btn-link" target="_blank"><span>{% trans 'View Map' %}</span><i class="icon-long-arrow-right"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="map"></div>
    </div>
</main>
<style>
    .contact-alert {
        margin-bottom: 20px;
        border-radius: 8px;
        padding: 10px 15px;
        font-size: 14px;
    }
    .alert-success {
        background: #e6ffed;
        border: 1px solid #2ecc71;
        color: #2ecc71;
    }
    .alert-error, .alert-danger {
        background: #ffe6e6;
        border: 1px solid #e74c3c;
        color: #e74c3c;
    }
    .invalid-feedback {
        color: #e74c3c;
        font-size: 13px;
        margin-top: 5px;
    }
</style>
{% endblock %}