apps/blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.blog_list, name='list'),
    path('detail/<int:pk>/', views.blog_detail, name='detail'),
]

apps/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('coming-soon/', views.coming_soon, name='coming_soon'),
    path('404/', views.error_404, name='error_404'),
]

apps/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('', views.products_view, name='products'),
    path('checkout/', views.checkout, name='checkout'),
    path('detail/', views.product_detail, name='detail'),
    path('wishlist/', views.wishlist, name='wishlist'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('blogs/', include('apps.blogs.urls', namespace='blogs')),
    path('products/', include('apps.products.urls', namespace='products')),
    path('', include('apps.pages.urls', namespace='pages')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<!-- molla/blog-listing.html  22 Nov 2019 10:04:10 GMT -->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <meta name="keywords" content="HTML5 Template">
    <meta name="description" content="Molla - Bootstrap eCommerce Template">
    <meta name="author" content="p-themes">
    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/images/icons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/images/icons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/icons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'assets/images/icons/site.html' %}">
    <link rel="mask-icon" href="{% static 'assets/images/icons/safari-pinned-tab.svg' %}" color="#666666">
    <link rel="shortcut icon" href="{% static 'assets/images/icons/favicon.ico' %}">
    <meta name="apple-mobile-web-app-title" content="Molla">
    <meta name="application-name" content="Molla">
    <meta name="msapplication-TileColor" content="#cc9966">
    <meta name="msapplication-config" content="{% static 'assets/images/icons/browserconfig.xml' %}">
    <meta name="theme-color" content="#ffffff">
    <!-- Plugins CSS File -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/owl-carousel/owl.carousel.css' %}">
    <!-- Main CSS File -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    {% block extra_css %}{% endblock %}

</head>

<body>
<div class="page-wrapper">
    {% url 'pages:home' as home_url %}
    {% if request.path == home_url %}
        {% include 'layout/header-home.html' %}
    {% else %}
        {% include 'layout/header-base.html' %}
    {% endif %}

    {% block content %}{% endblock %}

    {% include 'layout/footer.html' %}
</div>
<button id="scroll-top" title="Back to Top"><i class="icon-arrow-up"></i></button>

{% include 'layout/mobile-menu.html' %}

{% include 'layout/sign-in-modal.html' %}

<!-- Plugins JS File -->
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.hoverIntent.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'assets/js/superfish.min.js' %}"></script>
<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
<!-- Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>
{% block extra_js %}{% endblock %}
</body>


<!-- molla/blog-listing.html  22 Nov 2019 10:04:12 GMT -->
</html>

templates/layout/footer.html
{% load static i18n %}
<footer class="footer">
    <div class="footer-middle">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-lg-3">
                    <div class="widget widget-about">
                        <img src="{% static 'assets/images/logo.png' %}" class="footer-logo" alt="{% trans 'Footer Logo' %}" width="105" height="25">
                        <p>{% blocktrans %}Praesent dapibus, neque id cursus ucibus, tortor neque egestas augue, eu vulputate magna eros eu erat.{% endblocktrans %}</p>

                        <div class="social-icons">
                            <a href="#" class="social-icon" target="_blank" title="{% trans 'Facebook' %}"><i class="icon-facebook-f"></i></a>
                            <a href="#" class="social-icon" target="_blank" title="{% trans 'Twitter' %}"><i class="icon-twitter"></i></a>
                            <a href="#" class="social-icon" target="_blank" title="{% trans 'Instagram' %}"><i class="icon-instagram"></i></a>
                            <a href="#" class="social-icon" target="_blank" title="{% trans 'Youtube' %}"><i class="icon-youtube"></i></a>
                            <a href="#" class="social-icon" target="_blank" title="{% trans 'Pinterest' %}"><i class="icon-pinterest"></i></a>
                        </div><!-- End .social-icons -->
                    </div><!-- End .widget about-widget -->
                </div><!-- End .col-sm-6 col-lg-3 -->

                <div class="col-sm-6 col-lg-3">
                    <div class="widget">
                        <h4 class="widget-title">{% trans 'Useful Links' %}</h4><!-- End .widget-title -->

                        <ul class="widget-list">
                            <li><a href="../pages/about.html">{% trans 'About Molla' %}</a></li>
                            <li><a href="#">{% trans 'How to shop on Molla' %}</a></li>
                            <li><a href="#">{% trans 'FAQ' %}</a></li>
                            <li><a href="../pages/contact.html">{% trans 'Contact us' %}</a></li>
                            <li><a href="../auth/login.html">{% trans 'Log in' %}</a></li>
                        </ul><!-- End .widget-list -->
                    </div><!-- End .widget -->
                </div><!-- End .col-sm-6 col-lg-3 -->

                <div class="col-sm-6 col-lg-3">
                    <div class="widget">
                        <h4 class="widget-title">{% trans 'Customer Service' %}</h4><!-- End .widget-title -->

                        <ul class="widget-list">
                            <li><a href="#">{% trans 'Payment Methods' %}</a></li>
                            <li><a href="#">{% trans 'Money-back guarantee!' %}</a></li>
                            <li><a href="#">{% trans 'Returns' %}</a></li>
                            <li><a href="#">{% trans 'Shipping' %}</a></li>
                            <li><a href="#">{% trans 'Terms and conditions' %}</a></li>
                            <li><a href="#">{% trans 'Privacy Policy' %}</a></li>
                        </ul><!-- End .widget-list -->
                    </div><!-- End .widget -->
                </div><!-- End .col-sm-6 col-lg-3 -->

                <div class="col-sm-6 col-lg-3">
                    <div class="widget">
                        <h4 class="widget-title">{% trans 'My Account' %}</h4><!-- End .widget-title -->

                        <ul class="widget-list">
                            <li><a href="#">{% trans 'Sign In' %}</a></li>
                            <li><a href="../products/cart.html">{% trans 'View Cart' %}</a></li>
                            <li><a href="#">{% trans 'My Wishlist' %}</a></li>
                            <li><a href="#">{% trans 'Track My Order' %}</a></li>
                            <li><a href="#">{% trans 'Help' %}</a></li>
                        </ul><!-- End .widget-list -->
                    </div><!-- End .widget -->
                </div><!-- End .col-sm-6 col-lg-3 -->
            </div><!-- End .row -->
        </div><!-- End .container -->
    </div><!-- End .footer-middle -->

    <div class="footer-bottom">
        <div class="container">
            <p class="footer-copyright">
                {% blocktrans %}Copyright © 2019 Molla Store. All Rights Reserved.{% endblocktrans %}
            </p><!-- End .footer-copyright -->
            <figure class="footer-payments">
                <img src="{% static 'assets/images/payments.png' %}" alt="{% trans 'Payment methods' %}" width="272" height="20">
            </figure><!-- End .footer-payments -->
        </div><!-- End .container -->
    </div><!-- End .footer-bottom -->
</footer><!-- End .footer -->

templates/layout/header-base.html
{% load static %}
{% load i18n %}
{% load my_tags %}
<header class="header">
            <div class="header-top">
                <div class="container">
                    <div class="header-left">
                        <div class="header-dropdown">
                            {% get_current_language as current_lang %}
                            {% get_available_languages as all_langs %}
                            <a href="#">{{ current_lang }}</a>
                            <div class="header-menu">
                                <ul>
                                    {% for lang in all_langs %}
                                        {% if current_lang != lang.0 %}
                                            <li><a href="{% get_full_url request lang.0 %}">{{ lang.0|upper }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </div><!-- End .header-menu -->
                        </div><!-- End .header-dropdown -->
                    </div><!-- End .header-left -->

                    <div class="header-right">
                        <ul class="top-menu">
                            <li>
                                <a href="#">Links</a>
                                <ul>
                                    <li><a href="tel:#"><i class="icon-phone"></i>Call: +0123 456 789</a></li>
                                    <li><a href="{% url 'products:wishlist' %}"><i class="icon-heart-o"></i>{% trans 'Wishlist'%}<span>(3)</span></a></li>
                                    <li><a href="{% url 'pages:about' %}">{% trans 'About Us'%}</a></li>
                                    <li><a href="{% url 'pages:contact' %}">{% trans 'Contact Us'%}</a></li>
                                    <li><a href="#signin-modal" data-toggle="modal"><i class="icon-user"></i>{% trans 'Login'%}</a></li>
                                </ul>
                            </li>
                        </ul><!-- End .top-menu -->
                    </div><!-- End .header-right -->
                </div><!-- End .container -->
            </div><!-- End .header-top -->

            <div class="header-middle sticky-header">
                <div class="container">
                    <div class="header-left">
                        <button class="mobile-menu-toggler">
                            <span class="sr-only">{% trans 'Toggle mobile menu'%}u</span>
                            <i class="icon-bars"></i>
                        </button>

                        <a href="{% url 'pages:home' %}" class="logo">
                            <img src="{% static 'assets/images/logo.png' %}" alt="Molla Logo" width="105" height="25">
                        </a>

                        <nav class="main-nav">
                            <ul class="menu sf-arrows">
                                {% url 'pages:home' as home_url %}
                                {% url 'pages:about' as about_url %}
                                {% url 'pages:contact' as contact_url %}
                                {% url 'blogs:list' as blogs_url %}
                                {% url 'products:products' as products_url %}
                                <li class="{% if request.path == home_url %}megamenu-container active{% endif %}">
                                    <a href="{% url 'pages:home' %}" class="sf-with-ul">{% trans 'Home' %}</a>
                                </li>
                                <li class="{% if request.path == products_url %}megamenu-container active{% endif %}">
                                    <a href="{% url 'products:products' %}" class="sf-with-ul">{% trans 'Products' %}</a>
                                </li>
                                <li class="{% if request.path == blogs_url %}megamenu-container active{% endif %}">
                                    <a href="{% url 'blogs:list' %}" class="sf-with-ul">{% trans 'Blogs' %}</a>
                                </li>
                                <li class="{% if request.path == about_url %}megamenu-container active{% endif %}">
                                    <a href="{% url 'pages:about' %}" class="sf-with-ul">{% trans 'About' %}</a>
                                </li>
                                <li class="{% if request.path == contact_url %}megamenu-container active{% endif %}">
                                    <a href="{% url 'pages:contact' %}" class="sf-with-ul">{% trans 'Contact' %}</a>
                                </li>
                            </ul><!-- End .menu -->
                        </nav><!-- End .main-nav -->
                    </div><!-- End .header-left -->

                    <div class="header-right">
                        <div class="header-search">
                            <a href="#" class="search-toggle" role="button" title="Search"><i class="icon-search"></i></a>
                            <form action="{% url 'products:products' %}" method="get">
                                <div class="header-search-wrapper">
                                    <label for="q" class="sr-only">Search</label>
                                    <input value="{{ request.GET.q }}"
                                           type="search" class="form-control" name="q" id="q" placeholder="Search in..."
                                           required>
                                </div><!-- End .header-search-wrapper -->
                            </form>
                        </div><!-- End .header-search -->
                        <div class="dropdown compare-dropdown">
                            <a href="#" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-display="static" title="Compare Products" aria-label="Compare Products">
                                <i class="icon-random"></i>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right">
                                <ul class="compare-products">
                                    <li class="compare-product">
                                        <a href="#" class="btn-remove" title="Remove Product"><i class="icon-close"></i></a>
                                        <h4 class="compare-product-title"><a href="{% url 'products:products' %}">Blue Night Dress</a></h4>
                                    </li>
                                    <li class="compare-product">
                                        <a href="#" class="btn-remove" title="Remove Product"><i class="icon-close"></i></a>
                                        <h4 class="compare-product-title"><a href="{% url 'products:products' %}">White Long Skirt</a></h4>
                                    </li>
                                </ul>

                                <div class="compare-actions">
                                    <a href="#" class="action-link">Clear All</a>
                                    <a href="#" class="btn btn-outline-primary-2"><span>Compare</span><i class="icon-long-arrow-right"></i></a>
                                </div>
                            </div><!-- End .dropdown-menu -->
                        </div><!-- End .compare-dropdown -->

                        <div class="dropdown cart-dropdown">
                            <a href="#" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-display="static">
                                <i class="icon-shopping-cart"></i>
                                <span class="cart-count">2</span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right">
                                <div class="dropdown-cart-products">
                                    <div class="product">
                                        <div class="product-cart-details">
                                            <h4 class="product-title">
                                                <a href="{% url 'products:products' %}">Beige knitted elastic runner shoes</a>
                                            </h4>

                                            <span class="cart-product-info">
                                                <span class="cart-product-qty">1</span>
                                                x $84.00
                                            </span>
                                        </div><!-- End .product-cart-details -->

                                        <figure class="product-image-container">
                                            <a href="{% url 'products:products' %}" class="product-image">
                                                <img src="{% static 'assets/images/products/cart/product-1.jpg' %}" alt="product">
                                            </a>
                                        </figure>
                                        <a href="#" class="btn-remove" title="Remove Product"><i class="icon-close"></i></a>
                                    </div><!-- End .product -->

                                    <div class="product">
                                        <div class="product-cart-details">
                                            <h4 class="product-title">
                                                <a href="{% url 'products:products' %}">Blue utility pinafore denim dress</a>
                                            </h4>

                                            <span class="cart-product-info">
                                                <span class="cart-product-qty">1</span>
                                                x $76.00
                                            </span>
                                        </div><!-- End .product-cart-details -->

                                        <figure class="product-image-container">
                                            <a href="{% url 'products:products' %}" class="product-image">
                                                <img src="{% static 'assets/images/products/cart/product-2.jpg' %}" alt="product">
                                            </a>
                                        </figure>
                                        <a href="#" class="btn-remove" title="Remove Product"><i class="icon-close"></i></a>
                                    </div><!-- End .product -->
                                </div><!-- End .cart-product -->

                                <div class="dropdown-cart-total">
                                    <span>Total</span>

                                    <span class="cart-total-price">$160.00</span>
                                </div><!-- End .dropdown-cart-total -->

                                <div class="dropdown-cart-action">
                                    <a href="{% url 'products:cart' %}" class="btn btn-primary">View Cart</a>
                                    <a href="{% url 'products:checkout' %}" class="btn btn-outline-primary-2"><span>Checkout</span><i class="icon-long-arrow-right"></i></a>
                                </div><!-- End .dropdown-cart-total -->
                            </div><!-- End .dropdown-menu -->
                        </div><!-- End .cart-dropdown -->
                    </div><!-- End .header-right -->
                </div><!-- End .container -->
            </div><!-- End .header-middle -->
        </header><!-- End .header -->

templates/layout/mobile-menu.html
{% load static %}
<!-- Mobile Menu -->
<div class="mobile-menu-overlay"></div><!-- End .mobil-menu-overlay -->

<div class="mobile-menu-container">
    <div class="mobile-menu-wrapper">
        <span class="mobile-menu-close"><i class="icon-close"></i></span>

        <form action="#" method="get" class="mobile-search">
            <label for="mobile-search" class="sr-only">Search</label>
            <input type="search" class="form-control" name="mobile-search" id="mobile-search" placeholder="Search in..."
                   required>
            <button class="btn btn-primary" type="submit"><i class="icon-search"></i></button>
        </form>

        <nav class="mobile-nav">
            <ul class="mobile-menu">
                <li class="active">
                    <a href="index.html">Home</a>

                    <ul>
                        <li><a href="index-1.html">01 - furniture store</a></li>
                        <li><a href="index-2.html">02 - furniture store</a></li>
                        <li><a href="index-3.html">03 - electronic store</a></li>
                        <li><a href="index-4.html">04 - electronic store</a></li>
                        <li><a href="index-5.html">05 - fashion store</a></li>
                        <li><a href="index-6.html">06 - fashion store</a></li>
                        <li><a href="index-7.html">07 - fashion store</a></li>
                        <li><a href="index-8.html">08 - fashion store</a></li>
                        <li><a href="index-9.html">09 - fashion store</a></li>
                        <li><a href="index-10.html">10 - shoes store</a></li>
                        <li><a href="index-11.html">11 - furniture simple store</a></li>
                        <li><a href="index-12.html">12 - fashion simple store</a></li>
                        <li><a href="index-13.html">13 - market</a></li>
                        <li><a href="index-14.html">14 - market fullwidth</a></li>
                        <li><a href="index-15.html">15 - lookbook 1</a></li>
                        <li><a href="index-16.html">16 - lookbook 2</a></li>
                        <li><a href="index-17.html">17 - fashion store</a></li>
                        <li><a href="index-18.html">18 - fashion store (with sidebar)</a></li>
                        <li><a href="index-19.html">19 - games store</a></li>
                        <li><a href="index-20.html">20 - book store</a></li>
                        <li><a href="index-21.html">21 - sport store</a></li>
                        <li><a href="index-22.html">22 - tools store</a></li>
                        <li><a href="index-23.html">23 - fashion left navigation store</a></li>
                        <li><a href="index-24.html">24 - extreme sport store</a></li>
                    </ul>
                </li>
                <li>
                    <a href="../products/products.html">Shop</a>
                    <ul>
                        <li><a href="category-list.html">Shop List</a></li>
                        <li><a href="category-2cols.html">Shop Grid 2 Columns</a></li>
                        <li><a href="../products/products.html">Shop Grid 3 Columns</a></li>
                        <li><a href="category-4cols.html">Shop Grid 4 Columns</a></li>
                        <li><a href="category-boxed.html"><span>Shop Boxed No Sidebar<span
                                class="tip tip-hot">Hot</span></span></a></li>
                        <li><a href="category-fullwidth.html">Shop Fullwidth No Sidebar</a></li>
                        <li><a href="product-category-boxed.html">Product Category Boxed</a></li>
                        <li><a href="product-category-fullwidth.html"><span>Product Category Fullwidth<span
                                class="tip tip-new">New</span></span></a></li>
                        <li><a href="../products/cart.html">Cart</a></li>
                        <li><a href="../products/checkout.html">Checkout</a></li>
                        <li><a href="../products/wishlist.html">Wishlist</a></li>
                        <li><a href="#">Lookbook</a></li>
                    </ul>
                </li>
                <li>
                    <a href="product.html" class="sf-with-ul">Product</a>
                    <ul>
                        <li><a href="product.html">Default</a></li>
                        <li><a href="product-centered.html">Centered</a></li>
                        <li><a href="product-extended.html"><span>Extended Info<span
                                class="tip tip-new">New</span></span></a></li>
                        <li><a href="product-gallery.html">Gallery</a></li>
                        <li><a href="product-sticky.html">Sticky Info</a></li>
                        <li><a href="product-sidebar.html">Boxed With Sidebar</a></li>
                        <li><a href="product-fullwidth.html">Full Width</a></li>
                        <li><a href="product-masonry.html">Masonry Sticky Info</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#">Pages</a>
                    <ul>
                        <li>
                            <a href="../pages/about.html">About</a>

                            <ul>
                                <li><a href="../pages/about.html">About 01</a></li>
                                <li><a href="about-2.html">About 02</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="../pages/contact.html">Contact</a>

                            <ul>
                                <li><a href="../pages/contact.html">Contact 01</a></li>
                                <li><a href="contact-2.html">Contact 02</a></li>
                            </ul>
                        </li>
                        <li><a href="../auth/login.html">Login</a></li>
                        <li><a href="../pages/faq.html">FAQs</a></li>
                        <li><a href="../pages/404.html">Error 404</a></li>
                        <li><a href="../pages/coming-soon.html">Coming Soon</a></li>
                    </ul>
                </li>
                <li>
                    <a href="blog.html">Blog</a>

                    <ul>
                        <li><a href="blog.html">Classic</a></li>
                        <li><a href="blog-listing.html">Listing</a></li>
                        <li>
                            <a href="#">Grid</a>
                            <ul>
                                <li><a href="blog-grid-2cols.html">Grid 2 columns</a></li>
                                <li><a href="blog-grid-3cols.html">Grid 3 columns</a></li>
                                <li><a href="blog-grid-4cols.html">Grid 4 columns</a></li>
                                <li><a href="blog-grid-sidebar.html">Grid sidebar</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">Masonry</a>
                            <ul>
                                <li><a href="blog-masonry-2cols.html">Masonry 2 columns</a></li>
                                <li><a href="blog-masonry-3cols.html">Masonry 3 columns</a></li>
                                <li><a href="blog-masonry-4cols.html">Masonry 4 columns</a></li>
                                <li><a href="blog-masonry-sidebar.html">Masonry sidebar</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">Mask</a>
                            <ul>
                                <li><a href="blog-mask-grid.html">Blog mask grid</a></li>
                                <li><a href="blog-mask-masonry.html">Blog mask masonry</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">Single Post</a>
                            <ul>
                                <li><a href="single.html">Default with sidebar</a></li>
                                <li><a href="single-fullwidth.html">Fullwidth no sidebar</a></li>
                                <li><a href="single-fullwidth-sidebar.html">Fullwidth with sidebar</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="elements-list.html">Elements</a>
                    <ul>
                        <li><a href="elements-products.html">Products</a></li>
                        <li><a href="elements-typography.html">Typography</a></li>
                        <li><a href="elements-titles.html">Titles</a></li>
                        <li><a href="elements-banners.html">Banners</a></li>
                        <li><a href="elements-product-category.html">Product Category</a></li>
                        <li><a href="elements-video-banners.html">Video Banners</a></li>
                        <li><a href="elements-buttons.html">Buttons</a></li>
                        <li><a href="elements-accordions.html">Accordions</a></li>
                        <li><a href="elements-tabs.html">Tabs</a></li>
                        <li><a href="elements-testimonials.html">Testimonials</a></li>
                        <li><a href="elements-blog-posts.html">Blog Posts</a></li>
                        <li><a href="elements-portfolio.html">Portfolio</a></li>
                        <li><a href="elements-cta.html">Call to Action</a></li>
                        <li><a href="elements-icon-boxes.html">Icon Boxes</a></li>
                    </ul>
                </li>
            </ul>
        </nav><!-- End .mobile-nav -->

        <div class="social-icons">
            <a href="#" class="social-icon" target="_blank" title="Facebook"><i class="icon-facebook-f"></i></a>
            <a href="#" class="social-icon" target="_blank" title="Twitter"><i class="icon-twitter"></i></a>
            <a href="#" class="social-icon" target="_blank" title="Instagram"><i class="icon-instagram"></i></a>
            <a href="#" class="social-icon" target="_blank" title="Youtube"><i class="icon-youtube"></i></a>
        </div><!-- End .social-icons -->
    </div><!-- End .mobile-menu-wrapper -->
</div><!-- End .mobile-menu-container -->